name: importtime

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  importtime:
    strategy:
      matrix:
        code: ['from pharmpy.modeling import *', 'from pharmpy.tools import *']
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
        include:
          - code: 'from pharmpy.modeling import *'
            threshold: 250000
          - code: 'from pharmpy.tools import *'
            threshold: 400000
          - platform: macos-latest
            threshold: 700000
          - platform: windows-latest
            threshold: 400000
          - code: 'from pharmpy.tools import *'
            platform: macos-latest
            threshold: 1200000
          - code: 'from pharmpy.tools import *'
            platform: windows-latest
            threshold: 620000
        exclude:
          - platform: windows-latest
            python-version: '3.10'

    runs-on: ${{ matrix.platform }}

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check import time of `${{matrix.code}}`
        uses: pharmpy-dev-123/gha-python-import-time@main
        with:
            code: ${{matrix.code}}
            threshold: ${{matrix.threshold}}
